[package]
name = "intel-8080-emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "i8080"
path = "src/lib.rs"

[[bin]]
name = "intel-8080-emu"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
